package ariba.buyer.vrealm_3.catalog;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Ariba Web Service
 *
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-25T13:44:32.572+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "WSCatalogItemSearch", 
                  wsdlLocation = "WSCatalogItemSearch.xml",
                  targetNamespace = "urn:Ariba:Buyer:vrealm_3") 
public class WSCatalogItemSearch extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:Ariba:Buyer:vrealm_3", "WSCatalogItemSearch");
    public final static QName WSCatalogItemSearchPortType = new QName("urn:Ariba:Buyer:vrealm_3", "WSCatalogItemSearchPortType");
    static {
        URL url = null;
        try {
            url = new URL("WSCatalogItemSearch.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSCatalogItemSearch.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "WSCatalogItemSearch.xml");
        }
        WSDL_LOCATION = url;
    }

    public WSCatalogItemSearch(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSCatalogItemSearch(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCatalogItemSearch() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSCatalogItemSearch(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSCatalogItemSearch(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSCatalogItemSearch(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WSCatalogItemSearchPortType
     */
    @WebEndpoint(name = "WSCatalogItemSearchPortType")
    public WSCatalogItemSearchPortType getWSCatalogItemSearchPortType() {
        return super.getPort(WSCatalogItemSearchPortType, WSCatalogItemSearchPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCatalogItemSearchPortType
     */
    @WebEndpoint(name = "WSCatalogItemSearchPortType")
    public WSCatalogItemSearchPortType getWSCatalogItemSearchPortType(WebServiceFeature... features) {
        return super.getPort(WSCatalogItemSearchPortType, WSCatalogItemSearchPortType.class, features);
    }

}
