package ariba.buyer.vrealm_3.catalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-25T13:44:32.568+03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:Ariba:Buyer:vrealm_3", name = "WSCatalogItemSearchPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WSCatalogItemSearchPortType {

    @WebMethod(operationName = "WSCatalogItemSearchOperation", action = "/Process Definition")
    @WebResult(name = "WSCatalogItemSearchReply", targetNamespace = "urn:Ariba:Buyer:vrealm_3", partName = "body")
    public WSCatalogItemSearchReply wsCatalogItemSearchOperation(
        @WebParam(partName = "body", name = "WSCatalogItemSearchRequest", targetNamespace = "urn:Ariba:Buyer:vrealm_3")
        WSCatalogItemSearchRequest body
    );
}
