
package ariba.buyer.vrealm_3.catalog;

import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.namespace.QName;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.interceptor.LoggingInInterceptor;
import org.apache.cxf.interceptor.LoggingOutInterceptor;

import ariba.buyer.vrealm_3.catalog.WSCatalogSearchTerm.Values;

/**
 * This class was generated by Apache CXF 2.7.17 2016-04-27T10:33:35.058+03:00
 * Generated source version: 2.7.17
 * 
 */
public final class WSCatalogItemSearchPortType_WSCatalogItemSearchPortType_Client {

	public static final QName SERVICE_NAME = new QName("urn:Ariba:Buyer:vrealm_3", "WSCatalogItemSearch");

	private WSCatalogItemSearchPortType_WSCatalogItemSearchPortType_Client() {
	}

	public static WSCatalogItemSearchReply searchInCatalog(URL wsdlURL, String valueField, String valueOperator,
			String valueItemNumber, String valueUser, String authorization) {

		WSCatalogItemSearch ss = new WSCatalogItemSearch(wsdlURL,
				WSCatalogItemSearchPortType_WSCatalogItemSearchPortType_Client.SERVICE_NAME);
		WSCatalogItemSearchPortType port = ss.getWSCatalogItemSearchPortType();

		Client cxfClient = ClientProxy.getClient(port);
		// HTTP headers
		Map<String, List<String>> headers = new HashMap<String, List<String>>();
		headers.put("Authorization", Arrays.asList(authorization));

		cxfClient.getRequestContext().put(org.apache.cxf.message.Message.PROTOCOL_HEADERS, headers);
		cxfClient.getInInterceptors().add(new LoggingInInterceptor());
		cxfClient.getOutInterceptors().add(new LoggingOutInterceptor());

		System.out.println("Invoking wsCatalogItemSearchOperation...");
		WSCatalogItemSearchRequest _wsCatalogItemSearchOperation_body = new WSCatalogItemSearchRequest();
		WSCatalogItemSearchRequest.WSCatalogSearchQueryRequestItem _wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItem = new WSCatalogItemSearchRequest.WSCatalogSearchQueryRequestItem();
		WSCatalogSearchQueryRequest _wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItem = new WSCatalogSearchQueryRequest();
		WSCatalogSearchQueryRequest.SearchTerms _wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItemSearchTerms = new WSCatalogSearchQueryRequest.SearchTerms();
		List<WSCatalogSearchTerm> _wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItemSearchTermsItem = new ArrayList<WSCatalogSearchTerm>();
		WSCatalogSearchTerm item = new WSCatalogSearchTerm();
		item.setField(valueField);
		item.setOperator(valueOperator);
		Values values = new Values();
		values.getItem().add(valueItemNumber);
		item.setValues(values);
		_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItemSearchTermsItem.add(item);
		_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItemSearchTerms.getItem()
				.addAll(_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItemSearchTermsItem);
		_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItem
				.setSearchTerms(_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItemSearchTerms);
		_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItem.setSort("");
		_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItem.setSortDirection("");
		_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItem.setUserId(valueUser);
		_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItem
				.setItem(_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItemItem);
		_wsCatalogItemSearchOperation_body
				.setWSCatalogSearchQueryRequestItem(_wsCatalogItemSearchOperation_bodyWSCatalogSearchQueryRequestItem);
		// _wsCatalogItemSearchOperation_body.setPartition("Partition736701678");
		// _wsCatalogItemSearchOperation_body.setVariant("Variant-1412729306");

		WSCatalogItemSearchReply _wsCatalogItemSearchOperation__return = port
				.wsCatalogItemSearchOperation(_wsCatalogItemSearchOperation_body);
		return _wsCatalogItemSearchOperation__return;

	}

}
